variables:
  GIT_CLEAN_FLAGS: -n

stages:
  - development
  - release
  - production

cache:
  key: "${CI_PROJECT_ID}-${CI_COMMIT_REF_SLUG}"
  paths:
    - node_modules/
    
before_script:
  #- export http_proxy=http://192.168.13.6:3128
  #- export https_proxy=http://192.168.13.6:3128

after_script:
  - docker image prune -f
  - echo "done"

development:
  stage: development
  script:
    - docker-compose -f docker-compose.dev.yml up -d --force-recreate --build dev-ceklok-coreplatform
  tags:
    - development
  only:
    - development

release:
  stage: release
  script:
    - docker-compose -f docker-compose.release.yml up -d --force-recreate --build release-ceklok-coreplatform
  tags:
    - release
  only:
    - release

production:
  before_script:
    - export http_proxy=http://192.168.13.6:3128
    - export https_proxy=http://192.168.13.6:3128
  stage: production
  script:
    - docker-compose -f docker-compose.prod.yml up -d --force-recreate --build prod-ceklok-coreplatform
  tags:
    - production
  only:
    - master
    - /^hotfix-[a-zA-Z0-9.]*/